name: Release Extension

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Setup pnpm
      run: npm install -g pnpm@10

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm config get store-dir)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      working-directory: src/extension
      run: pnpm install --frozen-lockfile

    - name: Set release version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "VERSION=${{ github.event.inputs.version}}" >> $GITHUB_ENV
        else
          echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
        fi
        echo "Using version: $VERSION"

    - name: Build extensions
      working-directory: src/extension
      run: pnpm run build:all

    - name: Zip dist folders
      working-directory: src/extension
      run: |
        zip -r cutfast-chrome-${VERSION}.zip dist-chrome
        zip -r cutfast-firefox-${VERSION}.zip dist-firefox

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        name: Release ${{ env.VERSION }}
        body: |
          ## Extension Downloads

          ### Firefox
          - [Download Firefox Extension](https://github.com/${{ github.repository }}/releases/download/${{ env.VERSION }}/cutfast-firefox-${{ env.VERSION }}.zip)

          ### Chrome
          - [Download Chrome Extension](https://github.com/${{ github.repository }}/releases/download/${{ env.VERSION }}/cutfast-chrome-${{ env.VERSION }}.zip)

          ## Installation Instructions

          ### Firefox Installation
          1. Download the Firefox extension zip file from the link above
          2. Extract the zip file to a folder on your computer
          3. Open Firefox and navigate to `about:addons`
          4. Click the gear icon (⚙️) in the top-right corner
          5. Select "Install Add-on From File..."
          6. Navigate to the extracted folder and select the `manifest.json` file
          7. Click "Open" to install the extension

          ### Chrome Installation
          1. Download the Chrome extension zip file from the link above
          2. Extract the zip file to a folder on your computer
          3. Open Chrome and navigate to `chrome://extensions/`
          4. Enable "Developer mode" in the top-right corner
          5. Click "Load unpacked" button
          6. Select the extracted folder containing the extension files
          7. The extension will be installed and appear in your extensions list

        files: |
          src/extension/cutfast-firefox-${{ env.VERSION }}.zip
          src/extension/cutfast-chrome-${{ env.VERSION }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
